[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/admin/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"