[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'DATABASE_URL: '\"$DATABASE_URL\" && npm run db:push && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"