[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Building production app...' && npm run build && echo 'Starting app...' && echo 'PORT: '$PORT && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"