[build]
builder = "nixpacks"

[deploy]
startCommand = "./start-production.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"