[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Starting app...' && echo 'PORT: '$PORT && echo 'DATABASE_URL: '$DATABASE_URL && npm run db:push --force && npm start"
# healthcheckPath = "/health"
# healthcheckTimeout = 600
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"